### ISSUE TITLE
Issues regarding emacs 24

### ISSUE THREAD

**Issue by tiagoantao** [clojure-emacs/inf-clojure#100]
This is not a bug per se, but a particularly annoying issue with emacs 24.

subr-x on emacs 24 does not have when-let, which means that inf-clojure does not work on emacs 24. It so happens that I suspect many installations out there are still emacs 24. When you install inf-clojure on emacs 24 it seems that it might work (the first suspicion is a configuration problem) when really it will not work at all.

So, I have a few suggestions

1. Support emacs 24 ;) . OK this might be asking too much, but quite a few users are still on 24 and update is not always trivial OR
2. Put a clear warning on the README that 25 is required AND
3. Tell people to delete their elpa caches if they upgrade from 24 to 25

Thanks

**Comment by bbatsov** [comment]
Well, if that's the only thing we've used from Emacs 24 I'd go with option 1. I see there's just a single usage of `when-let` in the entire codebase.

**Comment by arichiardi** [comment]
I think that support for subr-x has been added from 24.4.
-ar

**Comment by arichiardi** [comment]
Note that I have used Emacs 24.5 until yesterday (when I moved to 25.2) so we just need to specify that we don't support the version with no `subr-x` and `when-let`.

**Comment by bbatsov** [comment]
> I think that support for subr-x has been added from 24.4.

But when I wrote it (I'm the author of `subr-x`) those macros weren't in it. I think they were added in a subsequent release. I think CIDER defines them for backward compatibility and that's why this probably worked for you. It's not hard to expand one `when-let` into a `when` and a `let`, so this discussion seems kind of redundant. The fix is too simple to waste time discussing it.

**Comment by arichiardi** [comment]
Agree, maybe this can be one of those issues to start marking `starters` with a bright label? Of course I can take care of it as soon as I have more time.

**Comment by tiagoantao** [comment]
I am not totally sure if subr-x is the only thing, but I suspect it might be. My point is that even with the latest version of ubuntu inf-clojure does not work out of the box, so that will affect quite a few users.

I have since moved to emacs 25,  but obviously, if you release a patch I would test it with 24 and give feedback.

**Comment by arichiardi** [comment]
https://github.com/clojure-emacs/inf-clojure/pull/103 is ready for feedback :smile:

**Comment by tiagoantao** [comment]
@arichiardi  This is awesome, works perfectly. Thanks!

**Comment by arichiardi** [comment]
Just to confirm, which `emacs -version` are you on?

**Comment by tiagoantao** [comment]
24.5.1, I tried this with the stock emacs from Ubuntu 16.04 (the current LTS)
I will try at home (later) with raspbian (Raspberry Pi Debian version - the de facto standard on Raspberri Pi), but it also some recent 24, I am sure.

**Comment by tiagoantao** [comment]
Works on Rasbian/Raspsberry PI
