### ISSUE TITLE
Introduce a inf-clojure-override-cmd

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#108]
This is more of a feature than a bug.

Sometimes you are working on some project that has the normal `lein` or `boot` structure, but then for instance you have a `lumo` script.

One thing I do is to override `inf-clojure-lein-cmd` or `inf-clojure-boot-cmd` in `.dir-locals.el` with the `lumo` command, but it feels hacky and it is probably not very good either for `inf-clojure` beginners (I know that it was introduced recently, but I liked it better when we did not have any project detection).

This issue is here for discussing either a way to override the mechanism [here](https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L498) (if `inf-clojure-override-cmd` is non-nil we use that and skip the rest for instance), or a way to disable project detection - Emacs users are hackers, so given the function that detects the project, that could be used in `.dir-locals.el` for choosing the right command.

In any case, humbly asking for suggestions /cc @bbatsov.

Thank you folks ;)

**Comment by arichiardi** [comment]
Thoughts on this?

**Comment by bbatsov** [comment]
Closed by https://github.com/clojure-emacs/inf-clojure/commit/5d769201765fee21f7fa826db1655244a0361f97
