### ISSUE TITLE
comint-output-filter: (wrong-type-argument markerp nil)

### ISSUE THREAD

**Issue by martinklepsch** [clojure-emacs/inf-clojure#11]
```
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  comint-output-filter(#<process inf-clojure> "nREPL server started on port 4001 on host 0.0.0.0 - nrepl://0.0.0.0:4001\n")
```
I tried this in various projects and with various `inf-clojure-program` settings, but always end up there.
(I tried `boot repl`, `boot repl -c`, `lein repl`.) I set those via `(setq inf-clojure-program "...")`.

I learned that the error indicates that the process evaluates to `nil` but since it seems to have started properly I don't understand how this is possible. Also when I kill the `*inf-clojure*` buffer it tells me that there's a process attached to it and I have to type `yes` to actually kill it.

Any guidance on how to debug that further would be greatly appreciated :)

**Comment by bbatsov** [comment]
Setting a breakpoint in the problematic function is generally the way to go. I can't reproduce your problem with neither `lein` nor `boot`.

**Comment by martinklepsch** [comment]
Thanks, I'll give this a try. In the mean time do you have any ideas what else could cause this? 
E.g. I'm using Fish Shell could that be a potential cause?

**Comment by bbatsov** [comment]
> E.g. I'm using Fish Shell could that be a potential cause?

Pretty likely. Emacs is not known for its great support for fish (and inf-clojure communicates with a process running in a shell). Try using zsh or bash and you'll quickly confirm if fish is the problem.

**Comment by martinklepsch** [comment]
@bbatsov I changed by shell to bash and restarted my computer. Still same error. I verified that the shell has been set correctly via  `M-x getenv RET SHELL RET`.
```
(setq inferior-lisp-program "boot repl")
M-x inferior-lisp
```
Works fine. FWIW inferior lisp also works with fish as shell. Looking at the code of `inf-clojure` vs `inferior-lisp` here I don't see what's the difference here.

**Comment by bbatsov** [comment]
I'm at a loss then. I've tried the latest version from MELPA a few minutes ago and it works just fine for me. Guess something is different in your environment, but I have no idea what. 

What's your OS? What's your Emacs version?

**Comment by martinklepsch** [comment]
`M-x emacs-version`
```
GNU Emacs 24.4.50.1 (x86_64-apple-darwin14.0.0, NS appkit-1326.11 Version 10.10 (Build 14A299l)) of 2014-07-30
```
I'll try to remove `inf-clojure` again and some stuff like that. Let's see if that helps.

**Comment by martinklepsch** [comment]
I'm sure I'm doing something wrong... I just need to figure out what...

**Comment by bbatsov** [comment]
> I'm sure I'm doing something wrong... I just need to figure out what...

It's hard to do something wrong - `M-x inf-clojure` is pretty much everything one needs to do. :-)

I'm also using OS X and Emacs build from git, which leaves me even more puzzled.

**Comment by bbatsov** [comment]
You're using `clojure-mode` 4+, right?

**Comment by martinklepsch** [comment]
I think the issue might have been that I hooks like so:
```
(add-hook 'clojure-mode-hook #'inf-clojure-minor-mode)
(add-hook 'inf-clojure-mode-hook #'clojure-mode)
```
Now that I look at it it almost seems to ask for trouble.
I guess the takeaway is that one should disable all hooks before filing issues.

**Comment by bbatsov** [comment]
> (add-hook 'inf-clojure-mode-hook #'clojure-mode)

Yep, this is pretty wrong. :-)

**Comment by martinklepsch** [comment]
I thought the issue was that these hooks some how recursively call enable modes. Whats wrong with that hook?

**Comment by martinklepsch** [comment]
My thought was to get some syntax highlighting in the `inf-clojure` buffer. Whats the right way to achieve this w/o `clojure-mode` ?

**Comment by bbatsov** [comment]
> I thought the issue was that these hooks some how recursively call enable modes. Whats wrong with that hook?

You can't enable one major mode (clojure-mode) in another major mode (inf-clojure-mode). One supplants the other and breaks pretty much everything.

> My thought was to get some syntax highlighting in the inf-clojure buffer. Whats the right way to achieve this w/o clojure-mode ?

You can recycle clojure-mode's font-lock setup, but it won't work 100% correctly in the REPL buffer, because of things like prompts, subprompts, results, etc. Something like this might work:

```
(add-hook 'inf-clojure-mode-hook 'clojure-mode-font-lock-setup)
```

Not sure about other options.

**Comment by martinklepsch** [comment]
`'clojure-mode-font-lock-setup` isn't available to me but I guess I'll get this sorted out. Thanks for all the help :smile: :100:

**Comment by bbatsov** [comment]
Ops, seems I have renamed it to `clojure-font-lock-setup`.

**Comment by martinklepsch** [comment]
Thanks, that worked!
