### ISSUE TITLE
inf-clojure does not return prompt on entering new-line

### ISSUE THREAD

**Issue by slipset** [clojure-emacs/inf-clojure#113]
## Expected behavior
When opening a new inf-clojure process and typing `RET` multiple times, I expect to see 
multiple prompts:
```
Planck 2.8.1
ClojureScript 1.9.946
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
    Exit: Control+D or :cljs/quit or exit or quit
 Results: Stored in vars *1, *2, *3, an exception in *e

cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=> 
cljs.user=>
```

## Actual behavior
```
Process inf-clojure finished
Planck 2.8.1
ClojureScript 1.9.946
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
    Exit: Control+D or :cljs/quit or exit or quit
 Results: Stored in vars *1, *2, *3, an exception in *e

cljs.user=> 





```
## Steps to reproduce the problem
`M-x inf-clojure`
Type `RET` a couple of times. 

I can change this behaviour by redefining  `inf-clojure--send-string` so that it does not check for 
`(> (length string) 0)` when sending the command, and stuff works as I expect, eg
with 
```
(defun inf-clojure--send-string (proc string)
  (inf-clojure--set-repl-type proc)
      (comint-simple-send proc string))
```
things work as I expect.

**Comment by arichiardi** [comment]
So that change was introduced in order to avoid spurious prompts when the string to send is empty. There were cases when this was happening quite often (especially in lumo), so I put a patch that admittedly is not the best. I should probably remove it and investigate what actually happens now that we can dump the REPL activity.

**Comment by bbatsov** [comment]
Yeah, we should fix this.
