### ISSUE TITLE
Repl buffer sometimes has different inf-clojure-repl-type

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#116]
Probably due to some async interleaving sometimes I see the REPL buffer having a different repl type compared with the code buffer.

This means completion is failing with very strange errors.

**Comment by bbatsov** [comment]
Can you elaborate a bit more on this?

**Comment by arichiardi** [comment]
I will work out a repro, but it seems that the `*inf-clojure*` buffer does not get the type. Maybe it is not propagated.

**Comment by bbatsov** [comment]
Maybe it really be best if we also added some easy way to set the type of the REPL buffer manually - quite handy in such cases.

I'd also love to have a version of the start command that also asks you what type of REPL to start, so you just know everything is setup correct and nothing can go wrong. I recall recently seeing some error about the auto-detecting of the REPL type and this got me started thinking in this direction.

**Comment by arichiardi** [comment]
I like the idea very much, sometimes you want that. For this particular issue though, maybe the var should be made global or each buffer should have its own and the content updated after detection (if even possible in emacs)

**Comment by bbatsov** [comment]
Each buffer can have its own - that's the concept of buffer local variables in Emacs. https://www.gnu.org/software/emacs/manual/html_node/elisp/Buffer_002dLocal-Variables.html

Should be pretty easy to implement.
