### ISSUE TITLE
let*: Symbol’s function definition is void: seq-filter

### ISSUE THREAD

**Issue by austinhaas** [clojure-emacs/inf-clojure#141]
Commit introducing the issue: https://github.com/clojure-emacs/inf-clojure/commit/c3217c3fad1a06b0d40f25b64fffee8f115316d2

## Expected behavior

I should be able to evaluate expressions.

## Actual behavior

let*: Symbol’s function definition is void: seq-filter

## Steps to reproduce the problem

Start a repl.
Try to evaluate an expression.

### inf-clojure version information

master

### Emacs version

GNU Emacs 25.3.1 (x86_64-apple-darwin15.6.0, NS appkit-1404.47 Version 10.11.6 (Build 15G17023)) of 2017-11-10

### Operating system

macOS High Sierra Version 10.13.3

**Comment by arichiardi** [comment]
Very weird. To my knowledge the sequence functions were taken from https://github.com/NicolasPetton/seq.el

and that says:

> This package is now both in Emacs 25.1 and ELPA.

**Comment by austinhaas** [comment]
You are correct. It is included. It works if I (require 'seq).

**Comment by arichiardi** [comment]
Ok sorry I might have this loaded in my emacs already, and tests are not hooked up in Travis yet. Would you mind PR-ing?

**Comment by austinhaas** [comment]
Sure. No problem.

**Comment by austinhaas** [comment]
I'm having some trouble. If I (require 'seq) before inf-clojure is loaded, then it works fine. If I add the (require 'seq) to inf-clojure, I get a bunch of control characters (^G^G^G^G^G^G) printed to the REPL when I try to evaluate an expression.

Using git-bisect, I was able to narrow down the source of the control characters to this commit: f420c8a4d27c7c2dfea2ebee230d4d1b632a4e3f

**Comment by arichiardi** [comment]
Very odd, maybe you can add a PR and I can try it here as well

**Comment by arichiardi** [comment]
That commit had a bug in it, but it was not the one you describe, which REPL are you running against?

**Comment by austinhaas** [comment]
lein repl? I don't believe I'm specifying a REPL.

I do not see this control character issue on my Debian machine. I'll continue to investigate.

**Comment by arichiardi** [comment]
Yes the repl is inferred, will take a look as well...it should be testing it too now, also make sure you use dumb mode: 

https://github.com/clojure-emacs/inf-clojure/blob/master/README.md#caveats

**Comment by austinhaas** [comment]
Dumb mode = ":repl-options {:color false}"?

That doesn't seem to have any effect.

**Comment by arichiardi** [comment]
Yeah `lein` is a complex beast, I would go for a socket repl if I were you. You can also see what is going on better by enabling logging: https://github.com/clojure-emacs/inf-clojure#log-process-activity

**Comment by arichiardi** [comment]
I tried both with `lumo` and vanilla `cljs` socket repl and I never get extra characters.

**Comment by austinhaas** [comment]
Are those both for clojurescript? Is there a socket repl for clojure?

**Comment by arichiardi** [comment]
Yep https://dev.clojure.org/display/design/Socket+Server+REPL

**Comment by arichiardi** [comment]
Found a better pointer: https://stackoverflow.com/questions/34926360/how-can-i-start-a-socket-repl-in-clojure-1-8-from-leiningen-or-boot#34932745

**Comment by austinhaas** [comment]
Thanks!

**Comment by austinhaas** [comment]
FWIW, I haven't been able to figure out how to get a socket REPL running. I believe the only way is to run the clojure jar that is in my .m2 cache with the options given in the links above. And then connect to that from Emacs by specifying the address and port. That's a lot less convenient than C-c C-z from within Emacs. I can't find any instructions that show how to do that or how to make it easier.

And the recommendation to disable colors in the repl when using nrepl doesn't seem to work at all.

My repl is still broken on my MacOS machine. I'm still trying to debug.

**Comment by arichiardi** [comment]
Ok so following that SO question did not help? If you use lein you don't need to fiddle with jars, the config is written in the SO question I posted above. You could also use the new `clj` command, not at the keyboard now so cannot help more.

**Comment by arichiardi** [comment]
So the command would be:

```
clojure -J-Dclojure.server.repl='{:port 5555 :accept clojure.core.server/repl}'
```

**Comment by austinhaas** [comment]
Thanks for your help. I think I got it working.

I added `:jvm-opts ["-Dclojure.server.repl={:port 5555 :accept clojure.core.server/repl}"]` to my ~/.lein/profiles.clj

I start the REPL using `lein repl` in my source dir.

Within Emacs, I type `C-c M-c`, then localhost and 5555 to connect.

I do not see the control character issue.

I was also able to start and connect to a REPL using `clojure -J-Dclojure.server.repl='{:port 5555 :accept clojure.core.server/repl}'` after `brew install clojure`, but that did not seem to pick up any dependencies in my project.clj.

**Comment by arichiardi** [comment]
Yep `clojure` uses `deps.edn`, or you have to install a lein plugin for doing that. I am glad it is working!

You will have completions soon, I have to finish up a patch :smile:

**Comment by arichiardi** [comment]
If you have free time on your end, it would be good to capture this in a section of the Readme. Maybe some other folks are struggling with it.

**Comment by austinhaas** [comment]
Good idea. PR: https://github.com/clojure-emacs/inf-clojure/pull/145
