### ISSUE TITLE
comint-input-sender gets changed globally

### ISSUE THREAD

**Issue by mnewt** [clojure-emacs/inf-clojure#154]
## Expected behavior

Only set `comint-input-sender` in inf-clojure buffers

## Actual behavior

`(setq comint-input-sender 'inf-clojure--send-string)` in `inf-clojure-minor-mode` appears to set `comint-input-sender` globally for all comint derived buffers.

## Steps to reproduce the problem

`emacs -Q`

```emacs-lisp
(setq package-archives
        '(("gnu"   . "https://elpa.gnu.org/packages/")
          ("melpa" . "https://melpa.org/packages/"))
        use-package-always-ensure t)

(package-refresh-contents)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)

(use-package inf-clojure)
```

`M-x eval-buffer`

`M-x shell`

`M-x eval-expression comint-input-sender`

`inf-clojure--send-string`

### inf-clojure version information

2.1.0 (59868ff)

### Emacs version

GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin17.7.0, NS appkit-1561.60 Version 10.13.6 (Build 17G65)) of 2018-08-19

### Operating system

macOS 10.13.6

## Proposed Solution

Changing `setq` to `setq-local` in `inf-clojure-minor-mode` seems to fix the issue for me. If agreed, I can send a pull request.

**Comment by arichiardi** [comment]
It sounds good to me, probably @bbatsov knows Elisp better to answer this question though.

**Comment by charignon** [comment]
@austinhaas did you get a chance to test that? Can you submit your commit as a PR?

**Comment by arichiardi** [comment]
Hi! He intended to send a commit but didn't I guess?

No time in my open source time but i can definitely can review and push buttons :smile:

**Comment by austinhaas** [comment]
Yeah, I just added the change @mnewt suggested. It seems to work for me. I sent a PR. mnewt should get credit, if possible.

**Comment by mnewt** [comment]
@austinhaas thanks for submitting the PR. I was waiting for feedback and then forgot about it. I don’t need credit :)
