### ISSUE TITLE
Occasional spontaneous injection of lumo.repl into socket REPL input

### ISSUE THREAD

**Issue by jafingerhut** [clojure-emacs/inf-clojure#166]
## Expected behavior

Using socket REPL should never "on its own" give an error like this one:
```
Syntax error (ClassNotFoundException) compiling at (REPL:5:1).
lumo.repl
```

## Actual behavior

I have occasionally seen this occur.  I do not yet have a way to consistently reproduce it, and I have only seen it happen 3 to 4 times over heavy use of inf-clojure with a socket REPL over a 2 week period, so it is not frequent enough to be serious.

## Steps to reproduce the problem

*This is extremely important! Providing us with a reliable way to reproduce
a problem will expedite its solution.*

I wish I had one.  One observation is that I believe every time this occurred, it was when I was running a socket REPL to a Clojure process started outside of Emacs, with the Emacs session started via command info-clojure-connect.  I only ever saw the error when evaluating a Clojure expression that took several minutes to evaluate before another REPL was printed, which might be a factor.  It did not consistently appear in that situation, though, only occasionally.

## Environment & Version information

I do not understand what environment is being asked about here.  I was using Clojure 1.10.1 and OpenJDK 11.0.3

### inf-clojure version information

2.1.0 according to M-x inf-clojure-display-version

### Lein/Boot version

Neither lein nor boot was involved.  Using clj/clojure CLI tool to start Clojure process in a terminal before connecting to it using inf-clojure-connect.  `clj -Sdescribe` shows version 1.10.1.447

### Emacs version

25.2.2

### Operating system

Ubuntu desktop Linux 18.04.2 (running inside a VM on top of OS X 10.13.6, if that makes a difference, but I sure hope it doesn't)

**Comment by arichiardi** [comment]
Ok never experienced that, please let me know when/if you find a repro. Sorry about the inconvenience!

**Comment by dpsutton** [comment]
I believe this has been fixed. The repl type could get a bit mixed up but this should be fixed now in the latest release.
