### ISSUE TITLE
inf-clojure-show-var-source only works if code was entered by hand in repl

### ISSUE THREAD

**Issue by vigilancetech-com** [clojure-emacs/inf-clojure#167]
## Expected behavior

it would show the source

## Actual behavior

shows nothing

## Environment & Version information

spacemacs develop branch

### inf-clojure version information

2.2.0-snapshot

### Lein/Boot version

n/a using lumo

### Emacs version

26.2

### Operating system

Windows 10

**Comment by dpsutton** [comment]
I believe this is fixed in all repl types now. I'm gonna close and allow you to reopen if not that's not the case.
