### ISSUE TITLE
testing dep assess breaks tests on emacs 25

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/inf-clojure#177]
thanks to the really helpful @Silex I've found the reason the tests have been failing.

Assess is a testing library included which requires seq. emacs 25 tops out at seq 2.3 and assess -> m-buffer -> seq 2.14. And there we have our blowup.

Wanted thoughts about how to clean this up:
1. don't test on emacs 25. Its pretty old and pretty reasonable to expect people to be on a later version. We still support 25 of course just no reason to complicate our tests. Downside is its easy to slip something in that breaks 25 support and we won't know for a while.
2. Inline what we need from assess. Either the actual functions or don't use the library but roll our own.
3. Delete these tests. These tests are all about completion bounds. Not sure how much benefit they confer.

Wanted to get your thoughts @bbatsov and then we can get the test runner green again.

**Comment by bbatsov** [comment]
> don't test on emacs 25. Its pretty old and pretty reasonable to expect people to be on a later version. We still support 25 of course just no reason to complicate our tests. Downside is its easy to slip something in that breaks 25 support and we won't know for a while.

That's fine by me.

> Delete these tests. These tests are all about completion bounds. Not sure how much benefit they confer.

Also fine by me. :-)

I think there's also the option of adding a newer `seq.el` deps for the tests. In general it'd be nice if we migrated the test suite to `buttercup` at some point, as that's what `clojure-mode` and CIDER are using. I think it's the best testing library for Emacs today, but I've spent too much time with RSpec and Jasmine on my day job, so I'm clearly biased. :-)

**Comment by bbatsov** [comment]
I've opted not to run the tests on Emacs 25.
