### ISSUE TITLE
inf-clojure-eval-region always sends a newline to inf-clojure process, even when not needed

### ISSUE THREAD

**Issue by otijhuis** [clojure-emacs/inf-clojure#18]
Currently `inf-clojure-eval-region` always sends a newline after sending the region text.

This often leads to showing multiple prompts because in most cases the region already contains a newline at the end. Then you end up with something like this:

```clojure
{:a 1}
user=>
user=>
```

Would be nice if it only added a newline when it doesn't have one already. Can create a PR if you like.

**Comment by bbatsov** [comment]
Yeah, sure. A PR would be welcome.
