### ISSUE TITLE
All strings sent to REPL are converted from multi-line to single-line

### ISSUE THREAD

**Issue by admiralbumblebee** [clojure-emacs/inf-clojure#187]
## Expected behavior

Text sent to REPL is sent as-is, without conversion or parsing.

I view this as expected behaviour given that this is traditionally how inferior-lisp works, and the standard clojure REPL supports multiline strings without issue.

## Actual behavior

inf-clojure [converts all strings to a single-line](https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L378) before sending to the comint process.

This causes [the 1024 TTY character limit per line](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=32438) problem on macOS to be frequently encountered in multiple scenarios.

There are at least 3 _related_ issues to this line of code:

https://github.com/clojure-emacs/inf-clojure/issues/152
https://github.com/clojure-emacs/inf-clojure/issues/40
https://github.com/clojure-emacs/inf-clojure/issues/183

and a branch with a (strange) potential fix:

https://github.com/clojure-emacs/inf-clojure/tree/fix-152

## Steps to reproduce the problem

Unnecessary.

## Other

I've been using inf-clojure with the referenced code (and associated calls) removed for 2 weeks full-time without issue in clj and cljs repls. I used babashka for a short period of time without issue as well.

I have not tried planck/lumo/joker.

**Comment by bbatsov** [comment]
It took me a while, but I found the original problem - https://github.com/clojure-emacs/inf-clojure/issues/7

**Comment by arichiardi** [comment]
If memory serves me well lumo is the one that caused problems. The fix looks good to me

**Comment by bbatsov** [comment]
No worries. I had forgotten about that patch, but I see that it bring back the subprompt issue in certain cases. If it only impacts Lumo, I guess that's fine - from what I know it's pretty much dead these days.

**Comment by dpsutton** [comment]
i believe it is officially deprecated. i suppose if we wanted to we could make this an option, automatically on for lumo, or just drop it entirely.

**Comment by arichiardi** [comment]
Agree we should proceed with the patch and special case for lumo maybe, in order not to break people...my 2c

**Comment by admiralbumblebee** [comment]
Has it been tried with Lumo? I can't even get Lumo to run on my machine.

**Comment by arichiardi** [comment]
I tried it when I wrote my last comment in the PR. An if on the repl type should be enough. The other option is breaking, which probably is ok as long as we write this in the Changelog (or maybe Bozhidar has a better idea)

**Comment by bbatsov** [comment]
Well, let's merge your patch and see what happens.

**Comment by admiralbumblebee** [comment]
Update after a week is that the merged fix has been working fine for me, and a few other people I know that I are using it actively.

**Comment by bbatsov** [comment]
Good to know! Thanks for following up!
