### ISSUE TITLE
Suggested addition: ClojureCLR support

### ISSUE THREAD

**Issue by E-A-Griffin** [clojure-emacs/inf-clojure#202]
`inf-clojure` seems to be the de facto tool in use for ClojureCLR development on emacs without this being officially supported. Adding an official option for `cljr` via a `lein-clr` repl would likely make it easier for developers to migrate from `clj`/`cljs` to `cljr`, without adding any significant bloating to the project.

**Comment by bbatsov** [comment]
I've never used ClojureCLR, but I'd be happy to add support for it. Is there something that you can tackle yourself via a PR?

**Comment by E-A-Griffin** [comment]
I'd be glad to!
