### ISSUE TITLE
Anything special needed for .cljc eval?

### ISSUE THREAD

**Issue by martinklepsch** [clojure-emacs/inf-clojure#24]
I'm trying to eval stuff from [this ns](https://github.com/martinklepsch/custom-comparator-set/blob/master/src/org/martinklepsch/cc_set.cljc) which contains some basic cljc stuff.

Now whenever I do that I get the following exception:
```
clojure.lang.LispReader$ReaderException: java.lang.RuntimeException: Conditional read not allowed
             java.lang.RuntimeException: Conditional read not allowed
clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: No matching ctor found for class org.martinklepsch.cc_set.impl.CustomComparatorSet, compiling:(/var/folders/ss/4qg3hk1d4nv40phg1360ng5w0000gn/T/boot.user1393283433339272685.clj:6:25)
     java.lang.IllegalArgumentException: No matching ctor found for class org.martinklepsch.cc_set.impl.CustomComparatorSet
clojure.lang.LispReader$ReaderException: java.lang.RuntimeException: Unmatched delimiter: )
             java.lang.RuntimeException: Unmatched delimiter: )
clojure.lang.LispReader$ReaderException: java.lang.RuntimeException: Unmatched delimiter: )
             java.lang.RuntimeException: Unmatched delimiter: )
```

I guess this is the critical bit:
```
[...] compiling:(/var/folders/ss/4qg3hk1d4nv40phg1360ng5w0000gn/T/boot.user1393283433339272685.clj:6:25)
```
It seems that the evaluation saves the relevant form to a file and evaluates this file(?) while assuming `.clj` file extension. At least that's how it looks to me :o) 

I'm using Boot which might also be the culprit here although I couldn't discover any obvious places in the code that writes to-be-evaluated expressions to a file.

If you think it's unlikely this is related to `inf-clojure` feel free to close this :)

**Comment by bbatsov** [comment]
`inf-clojure` is just sending the code to the REPL process, so I'm pretty puzzled by this. I'm guessing reader conditions should work just fine in the REPL. 

Unfortunately I have no knowledge of boot. @alandipert @micha any pointers would be welcome.

**Comment by martinklepsch** [comment]
Hey Bozhidar, I think you're right. I should have tested just copy and pasting a cljc form into the Boot repl earlier. I'll close this and follow up with Boot maintainers. Cheers, thanks for the quick reply and sorry for the confusion! :)

**Comment by martinklepsch** [comment]
Turns out it was just an old version of nREPL that was being loaded: https://github.com/boot-clj/boot/pull/343
