### ISSUE TITLE
Show eval results using overlays

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/inf-clojure#25]
I might be a good idea to copy CIDER's behaviour for showing eval results. Right now we show them only in the minibuffer, but CIDER can show results in the minibuffer, inline using overlays, or at both places at the same time, which is pretty cool (and more consistent with "modern editors").

**Comment by stardiviner** [comment]
+1 , really great feature.

**Comment by jethrokuan** [comment]
If you could point me in the right direction, I'm happy to try and help. Is all the code for overlays in [here](https://github.com/clojure-emacs/cider/blob/master/cider-overlays.el)?

**Comment by jethrokuan** [comment]
I'm gonna tackle this now

**Comment by bbatsov** [comment]
If someone is interested in working on this here are a few pointers - http://endlessparentheses.com/eval-result-overlays-in-emacs-lisp.html

**Comment by bbatsov** [comment]
On second thought - let's keep the scope of the project small.
