### ISSUE TITLE
inf-clojure-load-file default behavior not to switch to repl

### ISSUE THREAD

**Issue by oneness** [clojure-emacs/inf-clojure#26]
Hi,
I found myself using this fn a lot more and do not wan to to switch to repl by default, which takes over one of my windows that has a file I am looking at. And I do not see any way to disable it. Can we make it optional? I would be happy to do a PR.  Thanks

**Comment by bbatsov** [comment]
Yeah, we can certainly do this. PR welcome!

**Comment by oneness** [comment]
Thanks for your great work. Here is the PR:
https://github.com/clojure-emacs/inf-clojure/pull/27

**Comment by philc** [comment]
+1, this is one of the first things I worked around when trying inf-clojure. Thank you @oneness for working on the PR.

**Comment by bbatsov** [comment]
Btw, I'm curious what do you use load-file for. I'd expect people to be using eval-buffer most of the time.
