### ISSUE TITLE
inf-clojure gets into a bad state after some time

### ISSUE THREAD

**Issue by philc** [clojure-emacs/inf-clojure#28]
I don't have precise reproduction steps, but after some time evaluating buffers and defuns, the output from these commands stops appearing in the `*inf-clojure*` buffer, failing with this error:

```
recursive-edit: Wrong type argument: markerp, nil
```

Bouncing the REPL (by deleting the process attached to the _inf-clojure_ buffer and killing the buffer) doesn't restore inf-clojure to a good state. I need to restart Emacs to do that.

I haven't been able to produce a precise stack trace -- the debugger doesn't activate even after toggling debug-on-error. However, after putting some print statements in the code, I notice that even when inf-clojure is in a bad state, starting the REPL does result in `inf-clojure-preoutput-filter` being called with the correct output from `lein repl`, but the output never makes it into the `*inf-clojure*` buffer.

I'm using inf-clojure from melpa stable.

**Comment by bbatsov** [comment]
No one else ever reported this and I haven't been able to reproduce it myself, so I'll close this ticket for now.
