### ISSUE TITLE
Add an interactive command to bounce the REPL

### ISSUE THREAD

**Issue by philc** [clojure-emacs/inf-clojure#29]
Having a command to bounce a REPL would be helpful, since it's a common thing to do during clojure development.

Related: add a command to kill a REPL. Without this, it won't be clear to most users how to kill the underlying JVM that inf-clojure starts -- I don't believe killing the `*inf-clojure*` buffer does it.

This interactive command (or one of its helper functions) should take as a parameter the buffer who's REPL should be stopped/restarted, for ease of scripting multi-REPL workflows.

**Comment by bbatsov** [comment]
Just to be clear - "bounce" is the same as "restart" for you, right?

**Comment by philc** [comment]
That's right.
