### ISSUE TITLE
End of File during Parsing: inf-clojure-completions

### ISSUE THREAD

**Issue by jethrokuan** [clojure-emacs/inf-clojure#30]
`inf-clojure-completions` returns "end of file during parsing" for me:

```
~/Code/tob/src/tob $ inf-clojure-completions foo
End of file during parsing
```
I can confirm that the completion command works in the REPL however:

 ```
boot.user=> (complete.core/completions "hi")
("hiccup.compiler" "hiccup.core" "hiccup.def" "hiccup.page" "hiccup.util")
```

**Comment by jethrokuan** [comment]
after some hacking around, I found that the reason it failed was because the regex expression didn't strip the ANSI colors `boot repl` had, so all I had to do was to change boot repl to start with the --no-color flag. I'll close this issue.

**Comment by bbatsov** [comment]
Good to know.
