### ISSUE TITLE
Make inf-clojure more intelligent about inf-clojure-program

### ISSUE THREAD

**Issue by jethrokuan** [clojure-emacs/inf-clojure#31]
I think the inf-clojure command can be more intelligent about which command to when in a project file, since it uses the file to be aware of where the project root is.

https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L324

This would be a huge convenience for those who use both boot and lein.

**Comment by bbatsov** [comment]
I'm not quite certain what exactly are you suggesting. More info would be welcome.

**Comment by jethrokuan** [comment]
Correct me if I'm wrong, but I believe right now, it calls `inf-clojure-program`, regardless of whether it is a lein or boot project. This means running `inf-clojure` would only work on either one, boot, or lein projects.

**Comment by bbatsov** [comment]
Yeah, that's what happens. You'd like to be asked which one to use (lein or boot)?

**Comment by jethrokuan** [comment]
Perhaps based on which kind of project file found, project.clj or
build.boot, run a different inf-clojure-program? There are edge cases where
they have both files, this may pose a problem.

**Comment by bbatsov** [comment]
I see - you'd like us to have different defcustoms for the different types of projects. Yeah, this can certainly be done. Btw, even now you can override the variable `inf-clojure-program` or a per-project basis using `.dir-locals.el`.

**Comment by jethrokuan** [comment]
Thanks, I didn't know that. I'm leaving this here just for consideration:
there's a point where I believe it'd be taking inf-clojure too far. I feel
that abstracting away this detail from the user is not one of them.

**Comment by bbatsov** [comment]
I've finally got to taking care of this. It's much more primitive that CIDER's project type handling, but it gets the job done and I really want to keep `inf-clojure` as simple as possible.

**Comment by jethrokuan** [comment]
perfect! Thanks for all the work.

Regards,
Jethro Kuan
