### ISSUE TITLE
REPL prompt is stored as current input when navigating input history

### ISSUE THREAD

**Issue by oyvindstegard** [clojure-emacs/inf-clojure#35]
This applies at least to Emacs 25, I do not know about earlier versions.
0. Start clean Emacs instance with `emacs -Q`, load up required libs, `inf-clojure`, `clojure-mode`...
1. Start REPL with <kbd>M-x inf-clojure</kbd>
2. Input something and evaluate with <kbd>RET</kbd>
3. Describe variable `comint-stored-incomplete-input`, which should have the value `nil`, all OK so far.
4. Without inputting anything new, navigate to previous history item with <kbd>M-p</kbd>
5. Describe variable `comint-stored-incomplete-input` again, and now it contains the actual prompt with fontification and all:
`#("user=> " 0 7 ....)`
6. Try going back to current input with <kbd>M-n</kbd>, and the prompt gets inserted as actual "restored incomplete input", which is clearly wrong. So you end up with "user=> user=> ". This causes even bigger problems when using the default read-only-prompt setting (navigating history stops working properly).

**Comment by oyvindstegard** [comment]
Tried to fix it with the following commit:
https://github.com/oyvindstegard/inf-clojure/commit/f7d76544a865de8f12dbae621d4356708943ca53

**Comment by bbatsov** [comment]
Seems like a reasonable fix. You should have filed a PR.
