### ISSUE TITLE
(add-hook 'clojure-mode-hook #'inf-clojure-minor-mode) yields cryptic error

### ISSUE THREAD

**Issue by metaperl** [clojure-emacs/inf-clojure#37]
Hello, the evaluation of the form
`(add-hook 'clojure-mode-hook #'inf-clojure-minor-mode)
`

leads to the error message
`(inf-clojure-minor-mode clojure--check-wrong-major-mode)
`

Here is my code to load the minor mode via a hook:

```
(setq dldir "c:/Users/xyz/Downloads/")

(setq clj-mode (concat dldir "clojure-mode-master/clojure-mode-master"))
(add-to-list 'load-path clj-mode)
(require 'clojure-mode)

(setq inf-clj (concat dldir "inf-clojure-master/inf-clojure-master"))
(add-to-list 'load-path inf-clj)
(require 'inf-clojure)
(add-hook 'clojure-mode-hook #'inf-clojure-minor-mode)
```

And here is my emacs configuration:

> GNU Emacs 25.0.94.2 (x86_64-w64-mingw32)
>  of 2016-05-26 built on KAEL
> Windowing system distributor 'Microsoft Corp.', version 6.1.7601
> Configured using:
>  'configure --prefix=/tmp/emacs --without-imagemagick 'CFLAGS=-O2
>  -fomit-frame-pointer -g0''
> 
> Configured features:
> XPM JPEG TIFF GIF PNG RSVG SOUND DBUS NOTIFY ACL GNUTLS LIBXML2 ZLIB
> TOOLKIT_SCROLL_BARS
> 
> Important settings:
>   value of $LANG: ENU
>   locale-coding-system: cp1252
> 
> Major mode: Fundamental
> 
> Minor modes in effect:
>   recentf-mode: t
>   tooltip-mode: t
>   global-eldoc-mode: t
>   electric-indent-mode: t
>   mouse-wheel-mode: t
>   tool-bar-mode: t
>   menu-bar-mode: t
>   file-name-shadow-mode: t
>   global-font-lock-mode: t
>   blink-cursor-mode: t
>   auto-composition-mode: t
>   auto-encryption-mode: t
>   auto-compression-mode: t
>   buffer-read-only: t
>   line-number-mode: t
>   transient-mark-mode: t
> 
> Recent messages:
> Directory has changed on disk; type g to update Dired
> Quit
> Inf-Clojure minor mode enabled in current buffer
> or: No Clojure subprocess; see variable ‘inf-clojure-buffer’
> (inf-clojure-minor-mode clojure--check-wrong-major-mode) [2 times]
> Undo!
> C-x C-g is undefined
> Quit
> (inf-clojure-minor-mode clojure--check-wrong-major-mode)
> Mark set [5 times]
> Quit [2 times]
> 
> Load-path shadows:
> None found.
> 
> Features:
> (shadow sort mail-extr emacsbug message format-spec rfc822 mml mml-sec
> epg epg-config mm-decode mm-bodies mm-encode mail-parse rfc2231
> mailabbrev gmm-utils mailheader sendmail rfc2047 rfc2045 ietf-drums
> mail-utils inf-clojure easy-mmode comint ansi-color ring misearch
> multi-isearch ffap thingatpt url-parse auth-source cl-seq eieio byte-opt
> bytecomp byte-compile cl-extra cconv eieio-core gnus-util mm-util
> help-fns help-mode mail-prsvr password-cache url-vars recentf
> tree-widget wid-edit dired clojure-mode cl-macs gv rx derived edmacro
> kmacro easymenu align imenu cl-loaddefs pcase cl-lib time-date mule-util
> tooltip eldoc electric uniquify ediff-hook vc-hooks lisp-float-type
> mwheel dos-w32 ls-lisp disp-table w32-win w32-vars term/common-win
> tool-bar dnd fontset image regexp-opt fringe tabulated-list newcomment
> elisp-mode lisp-mode prog-mode register page menu-bar rfn-eshadow timer
> select scroll-bar mouse jit-lock font-lock syntax facemenu font-core
> frame cl-generic cham georgian utf-8-lang misc-lang vietnamese tibetan
> thai tai-viet lao korean japanese eucjp-ms cp51932 hebrew greek romanian
> slovak czech european ethiopic indian cyrillic chinese charscript
> case-table epa-hook jka-cmpr-hook help simple abbrev minibuffer
> cl-preloaded nadvice loaddefs button faces cus-face macroexp files
> text-properties overlay sha1 md5 base64 format env code-pages mule
> custom widget hashtable-print-readable backquote w32notify dbusbind w32
> multi-tty make-network-process emacs)
> 
> Memory information:
> ((conses 16 143227 6144)
>  (symbols 56 22806 0)
>  (miscs 48 246 170)
>  (strings 32 26531 4779)
>  (string-bytes 1 758578)
>  (vectors 16 15800)
>  (vector-slots 8 483980 9868)
>  (floats 8 227 217)
>  (intervals 56 3750 1413)
>  (buffers 976 24))

**Comment by bbatsov** [comment]
I can't reproduce this and I can't even imagine how this my happen. `inf-clojure` never uses the function that you're seeing your error message.
