### ISSUE TITLE
Namespaced maps not fully supported

### ISSUE THREAD

**Issue by yayitswei** [clojure-emacs/inf-clojure#39]
When I introduce a newline in a namespaced map, it seems to break the reader:

```
kb.views=> #::mb{:a 1 :b 2}
#:kb.models.messagebox{:a 1, :b 2}
kb.views=> #::mb{:a 1
                 :b 2}

RuntimeException EOF while reading, starting at line 1  clojure.lang.Util.runtimeException (Util.java:221)
```

**Comment by bbatsov** [comment]
Can't imagine why this is happening. We do no special input processing in the REPL buffer.

**Comment by yayitswei** [comment]
I just tried it in leiningen REPL and it fails there too. It could be a bug on the reader.

**Comment by bbatsov** [comment]
Yeah, probably the bug is there.

**Comment by halgari** [comment]
This is a bug in `lein` or nrepl,  it works fine in a bare Clojure repl created via `java -jar clojure.jar`. Doesn't work in `lein` using clojure alpha 14

**Comment by yayitswei** [comment]
Does it work in CIDER? If so, what is it doing differently?

**Comment by yayitswei** [comment]
This seems to be working in monroe as well, another nREPL client.

Btw, thanks so much for making both inf-clojure and CIDER. Both great pieces of software that have really benefited the community.

**Comment by bbatsov** [comment]
`inf-clojure` doesn't use nREPL at all - it simply runs a REPL process inside Emacs. Likely this is a bug in REPL-y. 

CIDER and Monroe implement their own custom REPLs (basically monroe copied the REPL code from CIDER).
