### ISSUE TITLE
Properly shut down processes

### ISSUE THREAD

**Issue by martinklepsch** [clojure-emacs/inf-clojure#41]
After debugging #40 I noticed that I still have lots of processes in the `run` state when looking at the `*Process List*` buffer. It does not seem to matter what/if any dependencies or code is loaded.

Probably my fault but is there a way to properly kill processes? Checked in M-x but couldn't find anything... (I'm using CMD + K now.)

**Comment by bbatsov** [comment]
Can I see a screenshot of your `*Process list*` buffer? I'm not sure what exactly is leaking for you.

**Comment by martinklepsch** [comment]
This is what it looks like after I started an inf-clojure process and then killed it. (I ran the `list-processes` command after I killed the process to ensure the listing is up-to-date.)

<img width="826" alt="screen shot 2017-03-01 at 17 18 23" src="https://cloud.githubusercontent.com/assets/97496/23455715/2dab5f38-fea3-11e6-8f8e-4a06474f4d20.png">

**Comment by bbatsov** [comment]
Seems that the problem is that 2 processes get created when you invoke something like `lein repl` or `boot repl` and just one of them gets associated with the inf-clojure buffer for obvious reasons (the buffer is just a presentation of this process). Not sure what we can do about the second process, though...

**Comment by bbatsov** [comment]
Forget this - it's just one process. I'm really puzzled why it doesn't die as Emacs asks to kill it when you kill the `inf-clojure` buffer.

**Comment by martinklepsch** [comment]
👍- happy I didn't report garbage haha. If I now kill a buffer with CMD+k, should this also correctly terminate the process or is it intended that's people use the new quit command from now on?

**Comment by bbatsov** [comment]
> If I now kill a buffer with CMD+k, should this also correctly terminate the process or is it intended that's people use the new quit command from now on?

You should use the new command. I've got no idea why `Control+k` is not working.

**Comment by martinklepsch** [comment]
Cool, thanks! And thanks for taking the time to look at this, just made another dash on the "Beers to buy for Bozhidar" dash list. 😄

**Comment by bbatsov** [comment]
You're welcome! At ClojureD a few people approached me asking for some inf-clojure improvements, because it was becoming a popular way to work with self-hosted ClojureScript REPLs like planck and lumo and I decided to give it a bit of love.
