### ISSUE TITLE
Optionally create new buffer on inf-clojure

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#42]
I started to use this a bit more again 😀 The usual thanks @bbatsov and contributors for your work.

I would like to have `inf-clojure` create a buffer that is different from the one I am launching it from. Like cider basically.

I understand this of course might be optional and I am already checking [switching-buffers](https://www.gnu.org/software/emacs/manual/html_node/elisp/Switching-Buffers.html). Any hint is super appreciated.

**Comment by bbatsov** [comment]
> I would like to have inf-clojure create a buffer that is different from the one I am launching it from. Like cider basically.

More details, please. :-) I'm not quite sure what you're aiming for.

**Comment by arichiardi** [comment]
Basically in cider whin I start the repl a new buffer is opened (unless I have zombies). In `inf-clojure` the repl is started in the same buffer. In other words  if I have one window with one frame to start with, with cider a `jack-in` will split in the window in two frames. In `inf-clojure` only one buffer is used. I don't know if there is a `cider` conf or something else actually (I use `pop-win` as well) I will need to double check.

**Comment by bbatsov** [comment]
Ah, got it. Yeah, we can totally make this configurable. It's actually configurable in CIDER as well - turned out not everyone was a fan of the new REPL window.

**Comment by hlolli** [comment]
this is what I do to get around this
```
(with-current-buffer (buffer-name)
      (inf-clojure inf-clojure-program)
      (split-window-sensibly) 
      (previous-window)
      (previous-buffer))
```
The only thing I find annoying about cider is that the cursor ends on the repl buffer after jack-in, I prefer to end up in the buffer Im working on with a repl window opened ready to accept my commands. I'm open for discussion what's the best default. At least not splitting the buffer seems at odd with what I would expect, (just my opinion).

**Comment by arichiardi** [comment]
Oh looks great ! Imho the cursors should either go at the end of the first top level form or stay put (configurable).

**Comment by bbatsov** [comment]
> The only thing I find annoying about cider is that the cursor ends on the repl buffer after jack-in, I prefer to end up in the buffer Im working on with a repl window opened ready to accept my commands.

That's already configurable in cider. :-)

**Comment by bbatsov** [comment]
@hlolli Some different code would be needed to have this as part of the mode. The only difficulty is figuring out how to plug into the comint init sequence as the new buffer gets created before `inf-clojure` is run. We can always adjust the windows in the the `inf-clojure-mode-hook`, but I'd prefer to do it at init time if possible.

**Comment by bbatsov** [comment]
Forget what I said, I'm an idiot. :-) Obviously the only thing that needs to be changed is the `inf-clojure` function and the changes needed there are trivial.

**Comment by bbatsov** [comment]
Feel free to open a separate issue about the cursor's position on repl start/swich.
