### ISSUE TITLE
Avoid prompting on doc, source, argument inspection

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#48]
Hi Bozhidar,

I would like to add an option that disables prompting at every `inf-clojure-show-*` function.
Cider's workflow is way more fluid. I was wondering whether we should have a `defcustom` for each and every command or a global one. Probably the latter.

Thanks a lot!

**Comment by bbatsov** [comment]
In cider it's a global config. I'm fine with adding a config for this here as well.

**Comment by arichiardi** [comment]
Should the recent `inf-clojure-prompt-on-set-ns` become global then? Probably you wouldn't want this as well.

**Comment by bbatsov** [comment]
> Should the recent inf-clojure-prompt-on-set-ns become global then?

Yeah, guess that'd be best. I totally forgot about it.
