### ISSUE TITLE
Newline in the wrong place on input (lumo)

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#53]
I have tried this in `lumo` not in `clojure`.

## Expected behavior

I expect:
```
speed-of-light.core=> (clojure.core/in-ns 'speed-of-light.aws)
...result...
```

## Actual behavior

Now we see:
```
speed-of-light.core=>
(
clojure.core/in-ns 'speed-of-light.aws)
...result...
```

## Steps to reproduce the problem

Execute any command except like `in-ns`, `doc`, ... in a `lumo` repl.

### inf-clojure version information

*latest master*

### Lein/Boot/Lumo version

*Lumo 1.2.0*

**Comment by bbatsov** [comment]
I'm guessing this didn't happen before? Likely it's some recent regression.

**Comment by arichiardi** [comment]
Maybe, I put it there for remind myself 😁

**Comment by arichiardi** [comment]
Yes the regression is due to https://github.com/clojure-emacs/inf-clojure/commit/a36d2a0473a211078af995ef9ea28f00fe1e6b32

**Comment by arichiardi** [comment]
So my code buffer now has a local var `inf-clojure-repl-type` but what if the `*inf-clojure*` buffer needs to know it's type? What is the best course of action here?

I tried to use the inspection function again but I need the repl type as early as in the `define-derived-mode` function.

**Comment by bbatsov** [comment]
> So my code buffer now has a local var inf-clojure-repl-type but what if the *inf-clojure* buffer needs to know it's type? What is the best course of action here?

Well, you simply check this variable. It's as simple as that. I guess I don't quite understand the problem you're facing. Do you want to setup the type earlier in the init process or something?

**Comment by arichiardi** [comment]
Yes I would like to check `inf-clojure-repl-type` before any text is outputted because I would like to filter based on the repl type. But `*inf-clojure*` at that point does not have it set.

**Comment by bbatsov** [comment]
> Yes I would like to check inf-clojure-repl-type before any text is outputted because I would like to filter based on the repl type.

No idea how you can do this - probably you'll have to plugin in the comint init or something. You'll have to do some exploration there. I'm guessing it'd be best if Lumo didn't output those special characters at all, though.

**Comment by arichiardi** [comment]
Oh definitely, I have opened an issue there. But I read better Eric's lisp than JavaScript 😀 No seriously, probably you are right, but until that is solved the Lumo Repl is usable only through socket.

**Comment by bbatsov** [comment]
I guess you can remove this filtering code, though. It probably affects negatively other REPLs as well.

**Comment by arichiardi** [comment]
Agree on this

**Comment by bbatsov** [comment]
Btw, we might also add a super simple interactive command to force the repl type for some REPL in case something is wrong with the detection logic or you want to override it. It would just prompt you for supported repl types and you'd pick one. You can use this as a workaround after starting a repl, but before any evaluation was done to set its type.

**Comment by arichiardi** [comment]
It is a good idea

**Comment by arichiardi** [comment]
To be fair a hook could be manually set on  the `comint` output as workaround I think.
So probably the best course of action here is to revert the commit above.

**Comment by bbatsov** [comment]
Yeah, that's probably true.

**Comment by bbatsov** [comment]
What's the state here?

**Comment by arichiardi** [comment]
Solved, the filtering has been removed/fixed.
