### ISSUE TITLE
Pre-output filter messes up output

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#54]
Hey @bbatsov,
I had a weird output going on and I was almost sure it could not be `lumo`:

```
cljs.user=> 
(
clojure.repl/doc defn)
...
```

So I checked this line:
https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L368

We were talking about sub-prompts, and to remove them, but why is it also prepending a `\n` there?
If I comment out the preoutput filter, I get a normal:

`cljs.user=> (lumo.repl/doc comment)`

Any hint on how I can improve this?

**Comment by bbatsov** [comment]
No idea. I've spent very little time working on `inf-clojure` - one day to get the initial version going and that was it. I pretty much don't remember any of the reasoning I've done in the past.

**Comment by arichiardi** [comment]
You gotta do what you gotta do 😀 I will have some fun I guess.

**Comment by bbatsov** [comment]
On the subject of newlines the only thing I remember is I had to append to a newline to all forms so they would actually get executed which was a bit odd. Now that there's the `inf-clojure-send-input` I guess it can simply check if something ends with a newline and append it if missing and you can drop the hardcoded newlines in the forms.

**Comment by arichiardi** [comment]
Also comint has `comint-simple-send` now

**Comment by bbatsov** [comment]
What's the state here?

**Comment by arichiardi** [comment]
Same, it looks like I have solved it in one of the iterations.
