### ISSUE TITLE
Add special handling for planck REPLs

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/inf-clojure#56]
Basically we need to extend what was done in #44 to cover planck as well, so all the `inf-clojure` functionality would work with planck properly.

This should be pretty easy and I would have done it myself if I knew the first thing about planck. :-)

**Comment by slipset** [comment]
Lucky you, it's my fun-Friday tomorrow, so I guess this will be the task.

**Comment by arichiardi** [comment]
I want to duplicate the load form defcustom today so that you have it tomorrow for planck ;)
