### ISSUE TITLE
Eldoc support

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/inf-clojure#6]
Figure out if it's possible to turn [this](https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L513) into proper eldoc support. Unfortunately for some reason it works super slow (unlike the completion code).

**Comment by otijhuis** [comment]
Am currently working on the eldoc support. Do you remember when it was slow exactly?
Looks like I have eldoc working and no slowness so far with the things I've tried.

**Comment by bbatsov** [comment]
Not sure exactly. I recall it was slow all the time because the code for getting the arglists took forever to executed for some reason. I actually referred to this code https://github.com/clojure-emacs/inf-clojure/blob/master/inf-clojure.el#L538

I had eldoc working if memory serves (probably the implementation was based on `ielm`'s eldoc as it was pretty simple). This was almost an year ago and my memory is fuzzy.

**Comment by otijhuis** [comment]
Ok. I created a PR. Probably needs a few changes but seems to work fine for me. 
No noticeable slowdowns that I can tell. Started with the cider eldoc support.

**Comment by otijhuis** [comment]
Ran into a problem with a clojurescript repl. The way it is now it uses `clojure.core/resolve` to find the arglist, and resolve doesn't exist in clojurescript.

**Comment by otijhuis** [comment]
@bbatsov , I think I found how to provide eldoc support for ClojureScript but all the solutions need an analysis environment. Do you happen to know how to get the analysis env of the currently running cljs repl? I could find how to create a new one, but can't seem to find how to get to an existing one.

**Comment by bbatsov** [comment]
My ClojureScript knowledge is next to none. :-)

On Saturday, 31 October 2015, Okke Tijhuis <notifications@github.com> wrote:

> @bbatsov <https://github.com/bbatsov> , I think I found how to provide
> eldoc support for ClojureScript but all the solutions need an analysis
> environment. Do you happen to know how to get the analysis env of the
> currently running cljs repl? I could find how to create a new one, but
> can't seem to find how to get to an existing one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/inf-clojure/issues/6#issuecomment-152746430>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by otijhuis** [comment]
Haha, guess I'm back to reading more source code then, in search of that illusive analysis env :)

**Comment by bbatsov** [comment]
Btw, it's ok to add the feature only for Clojure initially.

On Saturday, 31 October 2015, Okke Tijhuis <notifications@github.com> wrote:

> Haha, guess I'm back to reading more source code then, in search of that
> illusive analysis env :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clojure-emacs/inf-clojure/issues/6#issuecomment-152747068>
> .
>


-- 
Best Regards,
Bozhidar Batsov

http://www.batsov.com

**Comment by otijhuis** [comment]
For future reference (from Planck source):

Need to require `[cljs.analyzer :as ana]`

```

(defn resolve
  "Given an analysis environment resolve a var. Analogous to
   clojure.core/resolve"
  [env sym]
  {:pre [(map? env) (symbol? sym)]}
  (try
    (ana/resolve-var env sym
      (ana/confirm-var-exists-throw))
    (catch :default _
      (ana/resolve-macro-var env sym))))
```

**Comment by otijhuis** [comment]
I'll try for a few more days. If I can't find anything to go on for cljs I'll make a proper PR for Clojure only for the time being.

**Comment by bbatsov** [comment]
@otijhuis I'm guessing there's no progress with this, right?

**Comment by otijhuis** [comment]
@bbatsov unfortunately not. Haven't been able to do anything Clojure related lately.

**Comment by bbatsov** [comment]
You and me both. :-(

**Comment by arichiardi** [comment]
Probably now we can have a cljs repl type and do some fancy things with it 😀

**Comment by arichiardi** [comment]
@otijhuis could you share any initial work on this by any chance? I guess I can pick it up.

**Comment by otijhuis** [comment]
@arichiardi can't even remember if I had initial work :). Have been working full-time on other projects since I last commented.

**Comment by arichiardi** [comment]
@otijhuis ok no problem, I think btw you problem has been solved by https://github.com/clojure-emacs/cljs-tooling. I will close this for now.
