### ISSUE TITLE
Spurious output when first opened in lumo

### ISSUE THREAD

**Issue by arichiardi** [clojure-emacs/inf-clojure#63]
## Expected behavior

When first opening the repl and cursor is on code buffer, only `cljs.user =>` should appear.

## Actual behavior

The output of a command (for me it is arglists because the cursor was after fn symbol, but this varies) is printed in the `*inf-clojure*` buffer.

## Steps to reproduce the problem

`C-c C-z` with popup window enabled and move the cursor around in the code buffer.

or in `ielm`:

```
ELISP> (setq inf-clojure-repl-type nil)
nil
ELISP> (inf-clojure-arglist 'defn)
nil
```

### inf-clojure version information

*Latest master*

### Lein/Boot version

*Lumo latest master*

Reminder to self :sweat: :grimacing: :grinning:

**Comment by arichiardi** [comment]
This happens because the detection code of the repl type is not sync so it gets interleaved with the `arglists` call.

**Comment by arichiardi** [comment]
I found [elisp-latch](https://github.com/skeeto/elisp-latch) that happens to make things synchronous

**Comment by bbatsov** [comment]
> This happens because the detection code of the repl type is not sync so it gets interleaved with the arglists call.

The the arglists call shouldn't be producing any REPL output, so I'm a bit confused how it might be causing this.

**Comment by bbatsov** [comment]
@arichiardi ping

I'm assuming this is one of the things blocking us from a 2.0 release.

**Comment by arichiardi** [comment]
Yep, this still happens, I need to debug it.
