### ISSUE TITLE
Errors with figwheel repl

### ISSUE THREAD

**Issue by asultanpur** [clojure-emacs/inf-clojure#78]
I've been working with Figwheel REPL by following the docs [here](https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-with-Emacs-Inferior-Clojure-Interaction-Mode). After the upgrade to v2.0, I've been getting these errors. I ran `M-x toggle-debug-on-error` but can't seem to get more information.

```eldoc error: (args-out-of-range 9561)```

The REPL hangs and I cannot type any more expressions. The errors do not appear with the regular inf-clojure REPL.

Downgrading to v1.4.0 makes the errors go away.

## Steps to reproduce the problem

 - Use the lein-figwheel plugin and configure Emacs following this [guide](https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-with-Emacs-Inferior-Clojure-Interaction-Mode).
 - Type any ClojureScript expression in the REPL

### inf-clojure version information

v2.0

### Lein/Boot version

Lein v2.7.1
Lein Figwheel v0.5.10

### Emacs version

Tested with v24.5 and v25.1

### Operating system

Debian Sid

**Comment by bbatsov** [comment]
@arichiardi Can you take a look at this?

**Comment by arichiardi** [comment]
Sure I will test it. Just note that we don't have a cljs repl type at the moment, it defaults to a clj one. Thanks for reporting!

**Comment by arichiardi** [comment]
@asultanpur would it be difficult to try `master`? I think that #92 avoids the error and correctly (ok incorrectly but this is what we have at the moment) identify the REPL as `clj`.

**Comment by arichiardi** [comment]
Is there any feedback on this one? By the way I don't think there is a lot of value in having a `figwheel` mode in `inf-clojure` as there is nothing much to add to a cljs mode (e.g.: `figwheel` does not provide completions for instance).

**Comment by AdamFrey** [comment]
I've used figwheel with inf-clojure and it gives you a no-fuss cljs browser-connected repl in Emacs alongside you code compilation, so I think it's a worthwhile use case.

**Comment by arichiardi** [comment]
I use figwheel too but with `boot-figreload`...I am just saying that a REPL type here would not be of much help over a standard cljs REPL (that we don't have either at the moment).

Basically from a cljs REPL you would only need to set `inf-clojure-completion-form` to `nil` in order to disable it. Worth the convenience? I am open to votes :D

**Comment by AdamFrey** [comment]
oh, I misunderstood. I agree that inf-clojure likely doesn't need a `figwheel` mode.

**Comment by asultanpur** [comment]
@arichiardi Sorry for the delayed response. I have tested with master and I don't get any errors now and I'm able to run Cljs expressions.

**Comment by arichiardi** [comment]
Awesome, this can be closed then
