### ISSUE TITLE
etags navigation

### ISSUE THREAD

**Issue by martintrojer** [clojure-emacs/inf-clojure#8]
I've been using etags (via projectile) to do source-code navigation in with M-. and M-*.

Would be nice to add docs how to do this, like configuring exuberant tags to scan .clj files 

There are also some code changes to do for handling ns prefixes when finding tags and cycle through results.

**Comment by martinklepsch** [comment]
@martintrojer I ended up here because I read your blogpost. Would be sweet to have a "revised version" that uses `inf-clojure`. Just saying :see_no_evil: :grinning:

**Comment by martintrojer** [comment]
@martinklepsch check my blog again :)

**Comment by bbatsov** [comment]
@martintrojer Guess it makes sense to add `ns`-reloading upstream.

**Comment by martinklepsch** [comment]
@martintrojer awesome! immediately stole the ns reload function :)

**Comment by martintrojer** [comment]
I take that as a +1 for adding ns-reloading upstream :)

**Comment by martinklepsch** [comment]
A nice addition would be not to switch namespaces when there are errors while loading a namespace :)

**Comment by arichiardi** [comment]
I did not follow this, would love to get repl reload via `tools.namespace` here. Where is the @martintrojer blog post :smile: :smile: :wink: ?

**Comment by MalloZup** [comment]
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it
