### ISSUE TITLE
Rename inf-clojure-mode 

### ISSUE THREAD

**Issue by dpsutton** [clojure-emacs/inf-clojure#90]
I am learning inf-clojure thanks to the really nice video on [Lambda Island](https://lambdaisland.com/episodes/testing-clojurescript). I started an inf-clojure subprocess with `(inf-clojure "lein figwheel")` and this booted up a buffer with a repl. Then I went into my source buffer and of course, like most things, i put it into `inf-clojure-mode`. This is a mistake however, but not one that is obvious. This mode is used for the _process_ buffer, not the source buffer. The correct thing is to use the minor mode, of course. But this goes against standard convention I think.

I see that `inf-clojure-mode` is marked interactive but I don't see why this would ever be called by a human. It seems like you invoke a start inf-clojure function and this should put the repl into `inf-clojure-repl-mode` and then the minor mode would be obvious for the cljs buffer.

So my suggestion would be to make `inf-clojure-mode` non-interactive and to rename it to indicate that it is for a repl or process buffer rather than source buffer. It should be noted that I've only used it for a few minutes now but just wanted to point out a beginners impression. But its very nice!

**Comment by arichiardi** [comment]
I agree with this. Btw I know you found it already, but you need `inf-clojure-minor-mode` for code buffers.

**Comment by bbatsov** [comment]
> I see that inf-clojure-mode is marked interactive but I don't see why this would ever be called by a human. It seems like you invoke a start inf-clojure function and this should put the repl into inf-clojure-repl-mode and then the minor mode would be obvious for the cljs buffer.

Well, that's consistent with what modes like `inf-ruby` are doing. In the end of the day this mode is the mode of the REPL and minor mode is a bonus. I think that modes are always interactive commands and this is where the confusion comes from.

**Comment by dpsutton** [comment]
ah so it is. Well carry on then
