### ISSUE TITLE
inf-clojure-set-ns hangs Emacs

### ISSUE THREAD

**Issue by AdamFrey** [clojure-emacs/inf-clojure#96]
## Expected behavior
Changing inf-clojure repl namespace with `inf-clojure-set-ns`
## Actual behavior
Emacs hangs, and I have to kill it from my process manager. I tested this with different clojure source code projects and both `lein repl` and `boot repl` and it made Emacs hang consistently for me.

## Steps to reproduce the problem
- Run `inf-clojure`
- Evaluate one clojure buffer with `C-c C-k`
- Change to another clojure buffer
- Run `inf-clojure-set-ns`
### inf-clojure version information
20170710.708

### Lein/Boot version
Lein 2.7.1
Boot 2.7.2-SNAPSHOT

### Emacs version

25.1.1

### Operating system
Ubuntu 17.04

**Comment by arichiardi** [comment]
Can reproduce (both `lein` and `boot`)

**Comment by AdamFrey** [comment]
For what it's worth, changing the body of `inf-clojure-set-ns` to use `comint-simple-send` instead of `comint-proc-query` gives me a working function.

**Comment by arichiardi** [comment]
I think I need to use `inf-clojure-process-response` in all these functions now, in my experience it is more reliable.
